# Generated by Django 3.1.7 on 2021-02-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_Type',
            field=models.CharField(choices=[('Full-Time', '24h-Time'), ('Part-Time', '9h-Time')], max_length=20),
        ),
    ]
