# Generated by Django 3.1.7 on 2021-02-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_auto_20210220_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
